version: 2
jobs:
  web-build:
    docker:
      - image: node:10.15.2-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --dev
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - dist/
  deploy:
    docker:
      - image: node:10.15.2-alpine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            npm config set unsafe-perm true
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@tigercat2000.dev"
            git config user.name "ci-build"
      - run:
          name: Deploy to gh-pages
          command: gh-pages --dist dist

workflows:
  version: 2
  build:
    jobs:
      - web-build
      - deploy